package com.tony.tradinglab.discovery.domain;

public enum CandidateQualityReason {

    // 긍정
    REVENUE_ACCELERATING,
    PROFITABILITY_IMPROVING,
    FCF_IMPROVING,
    FCF_TURNAROUND,
    LOW_DEBT_BURDEN,
    NET_CASH,

    // 추가 조사 가치
    GROWTH_INVESTMENT_CANDIDATE,
    CAPEX_EXPANDING,
    CAPEX_DRIVEN_NEGATIVE_FCF,

    // 위험
    REVENUE_DECELERATING,
    PROFITABILITY_DETERIORATING,
    FCF_DETERIORATING,
    PERSISTENT_NEGATIVE_FCF,
    NEGATIVE_OPERATING_CASH_FLOW,
    SHORT_CASH_RUNWAY,
    HIGH_DEBT_BURDEN,
    VERY_HIGH_DEBT_BURDEN,
    DEBT_RISK_WARNING
}